---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: backups
spec:
  encryptedData:
    rootPassword: AgCNXw60JpXWiCj26eSgGn1sfSmTNZiOwfQJwNCEQRxwJxgHIHNGfcBd5SZG2GA2BE3eSmHJzIEaNjNlEO5N2FNDB0rtY0kRYsEMpMFqOfddKHghx0aTadOnWGi+36TSFIGreqvP23aHxD58GEMpz2gRmXj/X24TwKRWOUydX476rAz56UKcM4ZN8rbhOYlUXst7j8UxRlLZ789vhR1d0c3eNfcPfJ8KlAXeFiXbIAzR64Dvev0jvM218Xcn6T0h9Y2NwUq1sKT/7xD7MN8Miz7DoLg+JujLwCpgyt2i/Egrb1StsNCzPO5S9QZCL06dlaZ42IJS5LGXnulzaiEZxmjhQZI+i2kCNtNFCEyNC1YuJbVREH+HUBLw86bzM28RaNYSJhwjW++t9XdOaNa5uiLIe7dT3SRpIcW9b0/u/vQwu5q+c2pzO3Bnnd+i6qc5DjYp2AEXqsE5+KUFq9lpjX8z2M0smPE/WOh0+8kDe9Cibpee116KbV2rKRG34+bjNVquRvegmpHYBUxFX+A1PdzH1xjt5fzeQp/pQFUyqrkbrFeclfwhyQ8URT4eQ4A5iLnbE0gJlchCJZKVIG5iVbHwIlMn0icNGJHzkqAwPV6hgw5GDIf3q7G8//xW9b03pzgbAiB/AiaqaU2cQ3Fjii+Uh9/qky73evVPpYJLJrkue7/AEwwYBAREvD8SEl+27DNyOhdyIYELU3/LKdFS5Iw=
    rootUser: AgAaDjh5A3PWrKE42FQcgw9QU5QjQSKo4kALOppMnv4tT31qq2mdvdFb/T4WYB0KCe/pWhIS8k/aaNNg0luU4ZiGbg3qz46tfUYkXSfQ0aRkQ9ddqRNbhVMDcj6qr5kPnZave8clPG/Ck87i2Fk9bHuvatWpb0Ao0NCz0rN9mqJBy0d4ps4CwncUcIuz1pdTSWVbtO1eu6zaNaCSQxhtnncs42Hny26GkAnKWHQwTqQK8JghFFKr/GHjKNVpMWbnJMPtoR9NUmvOuXNhdULgo0QWWpFe9kY1HKthmQox0ffO0+m4o1rdRVI2r1n4uMZJBEWyj52rdvVnQHIwqlcRqLeHgEEiWuUu5P8OlFcGj4J5ZV6Ov5TsDfBCsN9fWseyYk60Y118eJwiSKpbDNN+kasDwb/TGTe9ogkXX/DvZwwVZxC7BzsX4g//Xof2+TrIaxLvoWlFDPrd0ttSWHD2j66wKpMj8ouu2667tNb3rBggmj+zT+TAHNzzxmXnAYyMxHxlxpBMLvGtBiUFtLprbRYKGIsqUpivLr24Cww0+n5EcVG8zaQTBgtE+oYWoRbsUNb5Qzyxmah8Jbtz20GZYC5aqcLndCpMj7aNvdxa6ntNUzuXGaO021d+bLUAQMXtNHOjTGBweLMjOeJqFSmBkX0qkFdV3AI6v2AxjEwio0IZcyHev/w5AS+JJqaVEIiKu0nN5gDjJ+CCexue
  template:
    metadata:
      name: minio-credentials
      namespace: backups
    type: Opaque
