apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace: backups
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: minio-credentials
  data:
    - secretKey: rootUser
      remoteRef:
        key: infrastructure/minio
        property: rootUser
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: rootPassword
      remoteRef:
        key: infrastructure/minio
        property: rootPassword
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
