---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: recyclarr-secrets
  namespace: arr
spec:
  encryptedData:
    secrets.yml: AgBnJ1C6pdLPTjFzE4qV+EDCHstD9auTXSeQCJMcGxRzzlbErpaSK/Ugud+Gx9UcX9b1EPL0jc6f3C+/qLwP+7fI3bFnVdhO26580luJAHHXWrCVoM+j+LRZfqcRra2ry3WQp3w7v0yg/X0Zl3rgXfa4Wsutq3RBEGW6C0jtQsZYzGX+WQrykBugH7/Fmhn0p4Xqm7PDwmybzpSm4oGGnZh4BPI7xCiu2ASyDU7pBTDTYIVFBrXjhkUqzSm3Btgi52Fux4C0TsZcII04qHIcYe9mQCabU/ANup0EeuIVE/5bx7N8k1kWxh9w5Wh0WHdm3GRkmTK5Zt2pFnFXlHSm0fBoFzxzbfjVLm2nJv83WksdQjD8z3EU4E4N7blPe/oBCB5XCEaGd9y1QvGLG2s+apU7dh+CJzjrbc0a6S+4FgBlFYkfzRSrgmSmVWir5NtBrEabJ/l8ZSWSCNmlIcFWZJq2si8QQfIKEcjChdDEePhPUr3G62E3A4114P3mn7bJSxQTGH/DEu9JUnux2OZYNnrXV4pMbtB9k6lkkjysZhEBmzH7miSPgeiFpu4PK+ODacQPtbFP7RGooB6weD6TVkJUralpExbMT4KJbRYtTGit/2PHV0hig/cx4jLfgoIxqQzJJ0KHyEpbVQGEn6bdcnzk/MYgwOUxCi5iuq53bUJoxo+XAyLUKi5vkq9QZWt8x7aA3X742YanjcXR9WuYYH9cFGKdr/sDk84n8jKAlNX0yz4IyffCaY0UKWhYzqiRr4N43WM/J7U1lWblLSgArmp33Yz+FJY7qdN2VllysRmxjCbgbWcPkxWec71exsP0NTTeeg==
  template:
    metadata:
      name: recyclarr-secrets
      namespace: arr
    type: Opaque
