apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-data
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3
    - hard
    - intr
    - rsize=1048576
    - wsize=1048576
    - async
    - noatime
  nfs:
    server: 192.168.1.158
    path: /volume/3378ed38-0d32-49cd-b634-08ab63e14f07/.srv/.unifi-drive/Media/.data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-data
  namespace: arr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Ti
  volumeName: arr-data
