apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-data
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.10.x
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-data
  namespace: arr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Ti
  volumeName: arr-data
