---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vpn-credentials
  namespace: arr
spec:
  encryptedData:
    password: AgBylo60SzsHy/kWW5wr6fiNLWaGSpCsgoXg/KEygM6kHED+XV1p/Ytr596EGcw0HYbW/dn8DctYrQzKZsAG8kfOTXJw1wXfKRugdUZqdjIxSnTIonzsOsBWPs/3hqztchhka/w1nVNMtiOIooYUTyASyNFpox27k6DQQXWzIUdT6Kn5wwo5bZukv2QiZglv58Vmw33//dCOI7vmO+ZYFpg7kFVBbnu/aYvmMqdVZB8EFX0bxoQy+vaOdxpXbhleAdJMKBBXmyiBXLTJetk/A2hDW08JaLNwgi7ioPyDSvPCWqkKxmBoqtFF4DVVG75j4AAl9Qkn5kiDo7C8uAyBsKSl02j50D0zZJBqaFfLlQUQvoFVDwlzEUlHXk8yrlncMGYqwCEv7sOE8ONVNq+Jhh81jNn0dWFDHFUjBpju8TyMcVeRRAQGs/PT3QOlmrqBXdAg4tnQYoS7zhZClEFwOXSbOCZyd2HIADOptnPmezknxWloGszGNQIFMaapQCF44LO8bqonYNu/3x+5pYU2MOrzeZ85NdWSxKrkATgvi31q/7OwyOm6RS5K1uKtaJIClN4+sIzkzoSj1pYxChng65Tr+f4fIb2lsFB7C1+RY0ZhWVgmHVPhzHg8j4H5OWkZevw0yLx5PMgJ792DdmA6sFaClPrbIeeoauYn8XIFUANvtxBkl2CKmpuEuhYNJ7KiEW0Tw1EJdR9tjwRGEtbVPVA=
    username: AgBMRsAYIyLcEA7/w1JpO6MjB8eCACQgBwxNXwM36Qq5xNFwo/+WG0rRHox5che4Ki5ZN3CINE2MZN4g+puNIqqPuYToksKB7xLiADG2BgkbviRjMhlyvKAmJ1JqEikRy7PFPy2lypWtBIW+z3k2NZykOmng18x2vu1BH6K2BuiFYG8Pt+X5xqosHwFZjlvBA7eMkWS2W55lz0Khr7V2rt1u3qied2XU1f0SyIBO0D2U8wuTTk9bXZVDWEr13nFz37hEl3+VVRY0Ba5S79melYqonT51aPsp9m4cS9nHIvmU+dyCVAk+5sIGsKYByeN/hizs2T6twZBVLHRBEV3EmRSlaf0U057NODTL19ljDgKLZLCU82AobisD100aa/x3gqeOmd//4fVzVgUVwDoYj/3zxf5Piqk3CCe9rG40DNcc28+vrvGbx6R5oO92AKwxrIwGUY6gjKkvTvSwDmibygh5leBZNa/bOu3m7D7KJAvwuNuA8Ymjltb9JgkGMZtfhb8qhWV2/Ty2SlAKvjEmh//h7/KeGyK7OvwLNfCh9iqveHDCczXsC+KTZw6KIqU8QtWtF8cAudH6dXsb0sSqogcyEep6gwCzmnlC9jKZz8kt9iX48uoum3FiaVaXJYZI6gOqp+UCS1rowmOAi0WQwos6k45YKY1jAnSht0cewBrprNE/b6eMlHD6G1SnvlKwx7pzbh+TBFwegw==
  template:
    metadata:
      name: vpn-credentials
      namespace: arr
    type: Opaque
