---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vpn-credentials
  namespace: arr
spec:
  encryptedData:
    OPENVPN_PASSWORD: AgAFwrXPYQGA3T39nJoFTM4vGGzDhs4RWwDe3In268YpkC2/5y/o5KgyOsnGcSCLWYSyXFB+4WAYZGQhUkbj75245Jumd/W0gfdsjMoXiJ/LXlXeVhZD71trXlZSXV+0bnGdnYcxSBPKIMakZc4wjEQ88Pcxa+KPNdZfr7eOlcT3udiXq/MliYhfw/OeZ/bZ2UAFhvyo+9V/CLMEeyjV3TcquFGToW5rbC+aooXPWp3lJudx4ifwgSBHpwgrC7+5OORXOe/+gmIV+yDDmDMErVCjaZIsJSGU2921aHPE2LbKSSHlPYPzyUTPdOfCTCnmfmrZCpRdaOvBT6pL3skG5rogcNvzWfAPeSLykS0OnAdzXaMUVZj5HDByDkV8t39L2OWID2PC3QsxhNUasohPJFonn0vKfg5lb6DNV3MYe5V0gQR4+smsyy4THXCNwU4P+rK/RlJcdUmOG956T2KfwqetaKa9tb7ueShkNToB2XXV2BfXCMg2IEVlne0M1r3ieyR0eIh4ml5GkxeYr4LvMdgmsFYgyBrCPhEF3FA0x4yn3BdwmTiR2ZkaKlzO/Dj/buEW0WWytgla7lx28UKzg1Owhffg/NJJ592GJu99QQc0AkfVy8GHTMil2Vrwo4y27xYgA8NhseL4Gj7ojq81ouEBNGJ+VSDJcyNbPZtogzj8ll2NkZPcooF3x5UOYOBrCOnxtVOEWHXxDOwfFWphH0g=
    OPENVPN_USER: AgA4io9HkzYfzUpnIzet2vpRQ3/oCcbe+c4kkTNZQlP9FbOpgkdIWi8hMO9K0g6UHNf8q44XX3v8rhKKroehbxYrALUC45aDPSV4bJHQ8/2nrnbzbcfoqcwZl8IupQndC4IR5xts8dTlMrb4A8Ii/kiE2Eh2ij6gyOgeVqODbw3/Fd5ZUdsr09gwY/oi6EoECSEAU4mg8aVOW6KSBs/IUgeg1xEyQAxSx+K5Gp5cMPr0aC73V4bIUULngXVBzohRk5W5jFy2ACK8izaQiguhqLqrpVWQUrevsW0W92hdcjbbzCj9Q19toLPBUPaV7mVTwvuEfF3uem4ZcmRod+uZoKyL40YZplEvov/8RT49U1i/c+ow/L84f0w4lJ7DqqE73jG0tBA7QCgT9zzXvarRZO7p14pY/TCx8HyC11xmC4/R2O6jkb6Wt+2i06cQDqTl3XHwgYCObrv0LyyQslt5JoNduQQen91toCHSP9zC4MWwkTtVxTf8GYlp4oXVQ9yPwvhKvhlFRHDtzilHQhaW4KcuG8IEhqwwNm5ezmuYs6GhhSUWrte+oMyOfMP93Qe7ccVsTBQPuaT+qSCQqXTfjWXPDituRLIg8xvV+VYFx8NpgHcfunvWYspbgFSPkDTjJ7uVpebb8ODRRiDLNBPyjyyQ1FEhwVwmlj3O9R7VqdUdevgT+9XXr6+2wskiICgZnTKD0t4heJTtPA==
  template:
    metadata:
      name: vpn-credentials
      namespace: arr
    type: Opaque
