vpa:
  enabled: false
securityContext:
  runAsNonRoot: true
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
controller:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 256Mi
  flags:
    on-by-default: "true"
    exclude-namespaces: "kube-node-lease,kube-public"

dashboard:
  replicaCount: 1
  flags:
    on-by-default: "true"
  resources:
    requests:
      cpu: 15m
      memory: 64Mi
    limits:
      cpu: 50m
      memory: 128Mi
