vpa:
  enabled: false

controller:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 256Mi
  flags:
    on-by-default: "true"
    exclude-namespaces: "kube-node-lease,kube-public"

dashboard:
  replicaCount: 1
  flags:
    on-by-default: "true"
  resources:
    requests:
      cpu: 15m
      memory: 64Mi
    limits:
      memory: 128Mi
