appName: media-operator-transcode
namespace: arr
sourceType: helm
chartRepo: ghcr.io/kyleseneker/media-operator
chartName: media-operator-transcode
chartVersion: "0.32.0"
createNamespace: false
hasResources: false
syncOptions:
  - ServerSideApply=true
  - ServerSideDiff=true
