apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - boot-configmap.yml
  - hooks-transforms-configmap.yml
  - openclaw-config.yml
  - openclaw-external-secret.yml
  - rbac.yml
  - skills-configmap.yml
  - workspace-configmap.yml
