apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-secrets
  namespace: openclaw
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: openclaw-secrets
  data:
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: apps/openclaw
        property: ANTHROPIC_API_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: SLACK_APP_TOKEN
      remoteRef:
        key: apps/openclaw
        property: SLACK_APP_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: SLACK_BOT_TOKEN
      remoteRef:
        key: apps/openclaw
        property: SLACK_BOT_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: apps/openclaw
        property: GITHUB_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: OPENCLAW_HOOKS_TOKEN
      remoteRef:
        key: apps/openclaw
        property: OPENCLAW_HOOKS_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: apps/exportarr
        property: sonarr-api-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: apps/exportarr
        property: radarr-api-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: PROWLARR_API_KEY
      remoteRef:
        key: apps/exportarr
        property: prowlarr-api-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
