appName: restore-authentik-database
namespace: restore-auth
sourceType: git
gitPath: k8s/clusters/homelabrestore01/apps/authentik-database
createNamespace: false
hasResources: false
syncOptions:
  - ServerSideApply=true
  - ServerSideDiff=true
