apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-authentik-db
  namespace: restore-auth
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
