apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    chart: nfs-subdir-external-provisioner
    targetRevision: 4.0.18
    helm:
      valuesObject:
        nfs:
          server: 192.168.1.158
          path: /volume/3378ed38-0d32-49cd-b634-08ab63e14f07/.srv/.unifi-drive/Media/.data
          mountOptions:
            - vers=3
            - hard
            - intr
        storageClass:
          name: nfs-client
          defaultClass: true
          reclaimPolicy: Retain
          pathPattern: "${.PVC.namespace}-${.PVC.name}"
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-provisioner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ServerSideDiff=true
