apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: nfs-subdir-external-provisioner
