apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr-secrets
  namespace: arr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: recyclarr-secrets
  data:
    - secretKey: secrets.yml
      remoteRef:
        key: apps/recyclarr
        property: secrets.yml
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
