apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr-secrets
  namespace: arr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: recyclarr-secrets
    template:
      engineVersion: v2
      data:
        secrets.yml: |
          sonarr_api_key: {{ .sonarrApiKey }}
          radarr_api_key: {{ .radarrApiKey }}
  data:
    - secretKey: sonarrApiKey
      remoteRef:
        key: apps/arr
        property: sonarr-api-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: radarrApiKey
      remoteRef:
        key: apps/arr
        property: radarr-api-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
