defaultPodOptions:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true
controllers:
  main:
    type: cronjob
    cronjob:
      schedule: 0 */6 * * *
      successfulJobsHistory: 1
      failedJobsHistory: 3
    containers:
      main:
        image:
          repository: ghcr.io/recyclarr/recyclarr
          tag: 8.5.1
        args:
          - sync
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        envFrom:
          - configMapRef:
              name: arr-env
persistence:
  config:
    type: configMap
    name: recyclarr-config
    globalMounts:
      - path: /config/recyclarr.yml
        subPath: recyclarr.yml
        readOnly: true
  secrets:
    type: secret
    name: recyclarr-secrets
    globalMounts:
      - path: /config/secrets.yml
        subPath: secrets.yml
        readOnly: true
