apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-qbittorrent
  namespace: restore-qbittorrent
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
