---
- name: Install NFS client packages
  ansible.builtin.apt:
    name:
      - nfs-common
    state: present

- name: Mount NAS via NFS
  ansible.posix.mount:
    path: "{{ nfs_mount_path }}"
    src: "{{ nas_ip }}:{{ nas_export_path }}"
    fstype: nfs
    opts: "vers=3,hard,intr"
    state: mounted
