defaultPodOptions:
  annotations:
    backup.velero.io/backup-volumes-excludes: data
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true
controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/unpackerr/unpackerr
          tag: v0.15.2
        env:
          UN_WEBSERVER_METRICS: 'true'
          UN_SONARR_0_URL: http://arr-sonarr.arr.svc.cluster.local:8989
          UN_RADARR_0_URL: http://arr-radarr.arr.svc.cluster.local:7878
          UN_QBIT_0_URL: http://arr-vpn-downloads.arr.svc.cluster.local:8080
        envFrom:
          - configMapRef:
              name: arr-env
          - secretRef:
              name: unpackerr-secrets
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 256Mi
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
service:
  main:
    controller: main
    ports:
      http:
        port: 5656
persistence:
  tmp:
    type: emptyDir
    globalMounts:
      - path: /tmp
  data:
    type: persistentVolumeClaim
    existingClaim: arr-data
    globalMounts:
      - path: /data
