---
cloud_init_image_url: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
cloud_init_template_id: 9000
cloud_init_template_name: "ubuntu-24.04-cloud"
cloud_init_storage: "local-lvm"
