apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-slack-webhook
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: alertmanager-slack-webhook
  data:
    - secretKey: url
      remoteRef:
        key: infrastructure/alertmanager-slack
        property: url
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
