---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhook
  namespace: monitoring
spec:
  encryptedData:
    url: AgCvYfwl9SMRHJbKF0BYNiJGGd9ADVWCGVheo5U424AaFrW5CgbgsbKV9Xdqnb9j7LaIPh5dh920d8/TimFZKTbVCV7lzZpvmdk7q0vSoSytxh5dmHyAvsCe1ljswSU2Bs7alP7Ikt1rTc7Tvf7KO2yWiDZTSLxM7veYn+Ie9IRsZYi8fsAOZVXqpD5uUXc0CDSlAmyPcMhv8hEsJRtxae+03eIUTWEv4r8CNrFmAF69Vn7UUVShopGdwIXWXAMJCOtzxN8F5uAVStvpc+bCMom3hFaF/SEJAQiSAkjT6nooFzkaC0mr4/fwxCZAtDtCiYkNQ3xTBrjel7halKTPWYJ8m9KciOx7T7B4B1VIA7EFoXmSdpRhr/JSzSUdu4o4TGWahCmYrCjaLnbV7s8wkjd+uAynhtmCL7leJqCgQscyMC8DKy5boagIBeifJ151WVJ0B90gTnje/6PPuVhrYkfR1/h2HGrCU+hVOQyl0UI5omBzEBcDo6wObFc6TLy58mqn3tSHHsylEAYBMWIqVLGIlXwXsLkWAaHdMsPMbOPIXwQeWcwb3uirsql+t71W8hwK3V+MZro2eF4KHBg/a/5DH7qGirXHpX5sdTEy3JC62dcwTGlzRCFv/huxyl0rVGNrcARY7/SBj1UceLAEpgMHnYgJQ9LVuBi2z7f5nmsOjy0fbBAVEbpMZ/hIZQb5D1ODaspZEF1xJxWTIIDZu6Nrr5wKRdBqlZsRMpVs4bGCTQKCPkR0AhsSNEHitx7c2Uj+c8Yr4q6AHF5F375hydwzOLVaJV39dAdGjASIcsLaiqw=
  template:
    metadata:
      name: alertmanager-slack-webhook
      namespace: monitoring
    type: Opaque
