---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc-secret
  namespace: monitoring
spec:
  encryptedData:
    GRAFANA_OIDC_CLIENT_SECRET: AgCF41n1dDMuSERafERqDBdp6RY2S+CjS+/M50OxWLWMrUfoHbyjUrELlTRlix6xpV+7EPIQB/VlKt6mn89jX3jyH15uC00fKewa5zgynS+NNgg/jKzM6b2RxNPngFC9YL2RWgOWxM9LaSs7RogFkBbNBe0PYlMI+EGA77B7lMn7Ye3Dx/H6gpapOJXb3DJwJ4tqzEqu4ohAlE5fPlkAbc9ZlQs6RT/SnDW9qO7f+W/JXB2wGuHe7aw1RQdZdTDXfz5QSmNOrSt185KNzyjkAUxQ23oRkfkt8ePmymNcDq3a29Fd9b4RgZ2cCTvJ62JwlQB7Xj4BZ/SHs/YNCYAVpq3dFk6hOKflN7p8wDy0CvmGE1VcqruQhloJDViKT+GzAmeyPpgSQzqldwu30yUq8jYRjB4yTlcLM/XjMVijEB/Jd2RX9ZQQmoEl7tDcZR9a/iFv0YznmJ+J5zwGUeCywYvxnOthUfG11FDahQ5zSHGM3K9nqSdIRRORya87+i8djbrYWEPPJUF9bmE1iB0X9uaIWQqVz4VVpOwVuu7IuU/HqPtzkR+C/PjX03v4zWXTzjsfCQ3oDWKPgAmRWV+2v38waSClYYCLN+lWwLyMUz3bQybtz+1+c8nSaRKRo+P/m/1aE3+LmFU5gL4lTI/Ic7AzKs/eRfuy3x/lXAjDIxrslt+W0ZrucPFxL10LfFGpf5AlgkmgWXag54gK+P/pvH4O27Af4XQNCIcrV8OZlQ+SkKCMtQqz0BIefPgynXV/nNOXDBcrvpSceCvEIAi6VmxxK5EKJa+pIpJretaLNo1C/LuF6LzJfPETlR/CKdM6PVDor0DamtjTHvSAPKJO6hYL0bvZs0UN4KgRgTdShwDcYw==
  template:
    metadata:
      name: grafana-oidc-secret
      namespace: monitoring
    type: Opaque
