---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAEu0/vsFEadXIF5JymiuDoi7wAWHYBLL7QY+l5+dGEqgKPjWxqXxoPHmSXf50LkpmgUhichZj66msXYOVzq8BT9JWcbm2xri/JbpJg0m3iBLkXmM7EMCDUkRgokJaTbx4onBcEs64mZYTxpXh7QZGP22cUIOeo9cz/pPXiC8YcbWyyXYesrFR5y2WoUE0cd9Vm57ydgE1JcyzauEw+3EaKOf/PjxWC44lGpX8xkUi/YFKYjWpD4RwkkXXgvt2m4H+eOebMfPyHTlZJ2XjHytk+X6j0a0IGE6ercXYoOxhauYwnEfQNRBKg2rR+VXqtHVp9EoSHJ2PSakEEMElPb1+xqdwko+ix6QgAUyRixXsHsAAzqH4AEBS+6vexQYzd6RK9iD32sSmS7ruNQO07bkLkNtnerGJbdbv5NgJnoXNFNVpXHNFUdKXLk2vmRyHcsIyk7SxDTBZFI71C+Fk5Z4qEcBV2siamNtiy0zbwvRe9fwLapu7lCCrlv0dNIhCvuseyhMHjN68ajlEPi6MkZIGAlF5SI65ZHdKQEAaro/L9NqR+g+EF36hDU8BxX5ASO/ZFj5qi3nKyXRNILzkLOKIykgSUT+FR3FFPVixxlfxPeEHr818Zy5QZKNnaHAvPxnGsq/zYbrOxf6mWc4KUl2s1p4LjGOVWqXHXc59vKW6v4gz2xRgzDo1Dg6xVmtqk1Ta4p91OWqt0G/D+9AmnsSE=
    admin-user: AgB2Tf/d27siL4Qb5aqlHm64WlfsZBKNhdDhoeLH8N7su7vhLz3n5cuKljrhJ19lbHNbeubZNywEn0Q61rxDIlnnxvqz/hsmnJ5Tx5ge4zXH/lgZIXSeQZIx3MXygJBVIpQlLBVjj+V5xciEW7HqZ6xHMio9Xb75rJ3a9ZsyJ6SYGomP3kyW/rl1CmFrc5eBL3pJ4z6fsrLgnz8fA9aY0tmbRI4RJ5vYyH1P2jK+rvDxABbG2H4VkuIQRkCYJuRFtZf6tI7g6mjbQ1ef7TUcZh4p8KCbA2NCqkTV8j4qhmCVrk2MhjU1oKToQUZpbGSjN5/Qpj3kn5ehKL8zf0hKSNpR4HQwBQDAhZUEznCjjH2LUQxgU8efF4Pyj0ODyTLvCeTXeiFVcvypkSu132mNnxYFEgL1fqI86sY6PbDOk3UDIpgym3D45cH98e8iOB9RFKksSlqZFfEn9qy2DbMY9o05ohosSbV2mTOb9V9yR7dZ+z1AGncYmSi7SIt/pa6f/t0cC0xFpZVBnGC9RwgvgsAl6rULdP/etZz47A1YD9nlZ76DfZT49oob8FoTAM49cc4yPVtObR5lYsa56En5Sagn/gg27aCJwj3rvDX0q9IZnMyNa5jGDOo95Y4M26T3OLRZg0b9TR1nGZqLDatY0wn+/tMJKgfP1cV8/aJ2VE00WPDCShNUlBAlC+gvU8MsYAGgE2CiDg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
