apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: grafana-admin
  data:
    - secretKey: admin-user
      remoteRef:
        key: infrastructure/grafana
        property: admin-user
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: admin-password
      remoteRef:
        key: infrastructure/grafana
        property: admin-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
