apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: grafana-oidc-secret
  data:
    - secretKey: GRAFANA_OIDC_CLIENT_SECRET
      remoteRef:
        key: infrastructure/grafana-oidc
        property: GRAFANA_OIDC_CLIENT_SECRET
