apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertmanager-openclaw-external-secret.yml
  - alertmanager-pdb.yml
  - alertmanager-slack-external-secret.yml
  - dashboard-cluster-capacity.yml
  - dashboard-namespace-resources.yml
  - grafana-external-secret.yml
  - grafana-oidc-external-secret.yml
  - homelab-rules.yml
  - httproutes.yml
  - prometheus-pdb.yml
