apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 3.7.1
    helm:
      valuesObject:
        admissionController:
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 384Mi
          container:
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 384Mi
        backgroundController:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 192Mi
        cleanupController:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
        reportsController:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 192Mi
        crds:
          annotations:
            argocd.argoproj.io/sync-options: Replace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ServerSideDiff=true
      - SkipDryRunOnMissingResource=true
