config:
  preserve: false
webhookLabels:
  app.kubernetes.io/managed-by: argocd
admissionController:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 384Mi
  container:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 384Mi
backgroundController:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 192Mi
cleanupController:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi
reportsController:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 192Mi
