defaultPodOptions:
  securityContext:
    runAsUser: 977
    runAsGroup: 988
    fsGroup: 988
    runAsNonRoot: true
  automountServiceAccountToken: false
controllers:
  main:
    type: cronjob
    cronjob:
      schedule: 0 */6 * * *
      concurrencyPolicy: Forbid
      successfulJobsHistory: 1
      failedJobsHistory: 3
      suspend: true
    containers:
      main:
        image:
          repository: ghcr.io/recyclarr/recyclarr
          tag: 8.7.2
        args:
          - sync
          - sonarr
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        env:
          TZ: America/Chicago
          SONARR_URL: http://restore-sonarr.restore-sonarr.svc.cluster.local:8989
persistence:
  state:
    type: persistentVolumeClaim
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /config
  tmp:
    type: emptyDir
    globalMounts:
      - path: /tmp
  config:
    type: configMap
    name: recyclarr-config
    globalMounts:
      - path: /config/recyclarr.yml
        subPath: recyclarr.yml
        readOnly: true
  secrets:
    type: secret
    name: restore-recyclarr-secrets
    globalMounts:
      - path: /config/secrets.yml
        subPath: secrets.yml
        readOnly: true
