apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.5.0/manifests/install.yaml
patches:
  - target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
    patch: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cmd-params-cm
      data:
        controller.diff.server.side: 'true'
  - target:
      kind: ConfigMap
      name: argocd-cm
    patch: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cm
      data:
        resource.exclusions: |
          - apiGroups:
            - cilium.io
            kinds:
            - CiliumIdentity
            - CiliumEndpoint
            clusters:
            - "*"
        resource.customizations.ignoreDifferences.apps_Deployment: |
          jqPathExpressions:
            - .spec.template.spec.hostUsers
        resource.customizations.ignoreDifferences.batch_CronJob: |
          jqPathExpressions:
            - .spec.jobTemplate.spec.template.spec.hostUsers
        resource.customizations.ignoreDifferences.apiextensions.k8s.io_CustomResourceDefinition: |
          jqPathExpressions:
            - .spec.conversion
  - target:
      kind: Deployment
      name: argocd-repo-server
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: argocd-repo-server
      spec:
        template:
          spec:
            initContainers:
              - name: copyutil
                command: ["sh", "-c"]
                args:
                  - /bin/cp --update=none /usr/local/bin/argocd /var/run/argocd/argocd && /bin/ln -sf /var/run/argocd/argocd /var/run/argocd/argocd-cmp-server
