---
- name: Configure Proxmox VE host
  hosts: all
  roles:
    - role: pve_network
      tags: [pve_network]
    - pve_repos
    - pve_iommu
    - role: pve_disable_wireless
      tags: [pve_disable_wireless]
    - pve_cloud_init
    - pve_pci_mapping
    - pve_api_token
    - pve_ups
    - role: tfc_agent
      tags: [tfc_agent]
