apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: exportarr-secrets
  namespace: arr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: exportarr-secrets
  data:
    - secretKey: sonarr-api-key
      remoteRef:
        key: apps/exportarr
        property: sonarr-api-key
    - secretKey: radarr-api-key
      remoteRef:
        key: apps/exportarr
        property: radarr-api-key
    - secretKey: prowlarr-api-key
      remoteRef:
        key: apps/exportarr
        property: prowlarr-api-key
    - secretKey: bazarr-api-key
      remoteRef:
        key: apps/exportarr
        property: bazarr-api-key
