{
 "title": "Sonarr",
 "description": "Sonarr metrics via Exportarr",
 "tags": [
  "exportarr",
  "sonarr"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Show Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarr_queue_total OR on() vector(0)",
     "legendFormat": "Queued"
    },
    { "expr": "sonarr_history_total", "legendFormat": "Completed" }
   ]
  },
  {
   "title": "Series",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sonarr_series_monitored_total", "legendFormat": "Monitored" },
    { "expr": "sonarr_series_total", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Seasons",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sonarr_season_monitored_total", "legendFormat": "Monitored" },
    { "expr": "sonarr_season_total", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Episodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarr_episode_downloaded_total",
     "legendFormat": "Downloaded"
    },
    { "expr": "sonarr_episode_total", "legendFormat": "Total" },
    { "expr": "sonarr_episode_missing_total", "legendFormat": "Missing" }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Storage Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sonarr_series_filesize_bytes" }
   ]
  },
  {
   "title": "Storage Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarr_rootfolder_freespace_bytes",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}
{
 "title": "Radarr",
 "description": "Radarr metrics via Exportarr",
 "tags": [
  "exportarr",
  "radarr"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Movies Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "radarr_queue_total OR on() vector(0)",
     "legendFormat": "Queued"
    },
    { "expr": "radarr_history_total", "legendFormat": "Completed" }
   ]
  },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "radarr_movie_missing_total", "legendFormat": "Missing" },
    { "expr": "radarr_movie_monitored_total", "legendFormat": "Monitored" },
    { "expr": "radarr_movie_total", "legendFormat": "Total" }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Storage Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "radarr_movie_filesize_total" }
   ]
  },
  {
   "title": "Storage Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "radarr_rootfolder_freespace_bytes",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}