apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: restore-grafana
  namespace: restore-vault
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: restore-vault
    kind: SecretStore
  target:
    name: restore-grafana
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: infrastructure/grafana
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: infrastructure/grafana
        property: admin-password
