appName: media-operator-indexers
namespace: arr
sourceType: helm
chartRepo: ghcr.io/kyleseneker/media-operator
chartName: media-operator-indexers
chartVersion: "0.22.0"
createNamespace: false
hasResources: true
syncOptions:
  - ServerSideApply=true
  - ServerSideDiff=true
