appName: arr-bazarr
namespace: arr
sourceType: helm
chartRepo: https://bjw-s-labs.github.io/helm-charts
chartName: app-template
chartVersion: 4.6.2
createNamespace: false
hasResources: true
syncOptions:
  - ServerSideApply=true
  - ServerSideDiff=true
