appName: media-operator
namespace: arr
sourceType: helm
chartRepo: ghcr.io/kyleseneker/media-operator
chartName: media-operator-pvr
chartVersion: "0.15.0"
createNamespace: false
hasResources: false
syncOptions:
  - ServerSideApply=true
  - ServerSideDiff=true
