---
all:
  children:
    control_plane:
      hosts:
        homelabk8s01-node-1:
          ansible_host: 192.168.10.50
    workers:
      hosts:
        homelabk8s01-node-2:
          ansible_host: 192.168.10.51
        homelabk8s01-node-3:
          ansible_host: 192.168.10.52
    gpu:
      hosts:
        homelabk8s01-node-3:
          ansible_host: 192.168.10.52
    k8s_cluster:
      children:
        control_plane:
        workers:
