appName: arr-seerr
namespace: arr
sourceType: helm
chartRepo: ghcr.io/seerr-team/seerr
chartName: seerr-chart
chartVersion: "3.3.0"
createNamespace: false
syncOptions:
  - ServerSideApply=true
  - ServerSideDiff=true
hasResources: true
