appName: reloader
namespace: kube-system
sourceType: helm
chartRepo: https://stakater.github.io/stakater-charts
chartName: reloader
chartVersion: 2.2.9
createNamespace: true
hasResources: true
syncOptions:
  - ServerSideApply=true
  - ServerSideDiff=true
