apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: reloader
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reloader
