apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-sonarr-config
  namespace: restore-sonarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
