apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-gpu-plugin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://intel.github.io/helm-charts
    chart: intel-device-plugins-gpu
    targetRevision: 0.31.1
    helm:
      valuesObject:
        sharedDevNum: 5
        nodeFeatureRule: false
  ignoreDifferences:
    - group: deviceplugin.intel.com
      kind: GpuDevicePlugin
      jqPathExpressions:
        - .spec
  destination:
    server: https://kubernetes.default.svc
    namespace: intel-gpu-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
      - ServerSideDiff=true
    retry:
      limit: 30
      backoff:
        duration: 10s
        maxDuration: 5m
        factor: 2
