apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: arr-default-deny
  namespace: arr
spec:
  endpointSelector: {}
  ingressDeny:
    - fromEntities:
        - world
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: arr-allow-gateway
  namespace: arr
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: cilium-envoy
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: arr-allow-internal
  namespace: arr
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: arr
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: arr-allow-monitoring
  namespace: arr
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring
