apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: auth-default-deny
  namespace: auth
spec:
  endpointSelector: {}
  ingressDeny:
    - fromEntities:
        - world
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: auth-allow-gateway
  namespace: auth
spec:
  endpointSelector: {}
  ingress:
    - fromEntities:
        - host
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: auth-allow-internal
  namespace: auth
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: auth
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: auth-allow-monitoring
  namespace: auth
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring
