apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: backups-default-deny
  namespace: backups
spec:
  endpointSelector: {}
  ingressDeny:
    - fromEntities:
        - world
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: backups-allow-internal
  namespace: backups
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: backups
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: backups-allow-monitoring
  namespace: backups
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring
