apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-credentials
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: authentik-credentials
  data:
    - secretKey: AUTHENTIK_BOOTSTRAP_PASSWORD
      remoteRef:
        key: infrastructure/authentik
        property: AUTHENTIK_BOOTSTRAP_PASSWORD
    - secretKey: AUTHENTIK_BOOTSTRAP_TOKEN
      remoteRef:
        key: infrastructure/authentik
        property: AUTHENTIK_BOOTSTRAP_TOKEN
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: infrastructure/authentik
        property: AUTHENTIK_POSTGRESQL__PASSWORD
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: infrastructure/authentik
        property: AUTHENTIK_SECRET_KEY
    - secretKey: postgresql-password
      remoteRef:
        key: infrastructure/authentik
        property: postgresql-password
