---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-cloud-credentials
  namespace: backups
spec:
  encryptedData:
    cloud: AgBf/CGcsDb4zUA9GJJpuyrjRTnAudjnET1y7vugGNab4Ru1+jIOBw1bCj/RXf20txOAcR2kGKwuVbLAEixRsWWxN8hykEmRH1vCaGPuSL7ZZIivxyj3/1AuKlz7bgOy9q7Kea5MpOZz25ZuvQ4Dqlt6zQ8naXiAseYTsigmfMG4RpC+1MtiPt+cg2GeMWqqQHOuM2EwUdXzGfFNeBDC48y8F7Tpt+8DTrNQLw7FF7cjCwbwBnaB9Xt6Gryj9ZTmHwJSO59GLsUyrVnEzcKp9kZQVnFoYb+d4rJ473GT27BUytjK9ZjugGXvsof8SxS50GWTerdD575edA9NrKk5ijYO2tXcfBOskp4MApr2TuF/A0REuLkByzCtROFZ33aYw+GYHIfMqJDi8dEZl2oZt6ooJwfQudIvOGnUVlujLT2h585TNgAeAYoiP00Idb/N+glSnEHI+e9ZOWgodadjf+ss2GySwIR+JS4MjlJtvBEbbLABqkLbAp7HL9m6NZr/yz4kJYsxDMll1JQyqqw9j8ViHbOaUGXdj+eqxzEz0UyYJUnb8aEhop5PHz6VBIjxI712c/Gf1dloGFsH4Q3BU/mzEteV7Az3Kt3owMHGY9NocbNSrewnp5crRM1DieO8dQJA4XEvxWLBEQmGTCid/B4Fmdi5qiWyEaCm3pM1LYd3wyaOc2vRUEEKswnMUsTQLar4hkAbkVW2qa8gGNzDOkfr36gZ5GFhn1LECRFdiq6Y3sZkGa1OubV8n5uc58p9i2OVuFzb20AuaNyWAkTYmzYyXaj1FWgIzR4zPFw9ll0Zb0w=
  template:
    metadata:
      name: velero-cloud-credentials
      namespace: backups
    type: Opaque
