apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-cloud-credentials
  namespace: backups
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: velero-cloud-credentials
  data:
    - secretKey: cloud
      remoteRef:
        key: infrastructure/velero
        property: cloud
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
