apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sb-harvester-secrets
  namespace: sb-harvester
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: sb-harvester-secrets
  data:
    - secretKey: SUPABASE_URL
      remoteRef:
        key: apps/sb-harvester
        property: SUPABASE_URL
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: SUPABASE_SERVICE_ROLE_KEY
      remoteRef:
        key: apps/sb-harvester
        property: SUPABASE_SERVICE_ROLE_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
