appName: media-operator-downloads
namespace: arr
sourceType: helm
chartRepo: ghcr.io/kyleseneker/media-operator
chartName: media-operator-downloads
chartVersion: "0.23.0"
createNamespace: false
hasResources: false
syncOptions:
  - ServerSideApply=true
  - ServerSideDiff=true
