apiVersion: v1
kind: ServiceAccount
metadata:
  name: restore-vault
  namespace: restore-vault
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restore-vault-token-review
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: restore-vault-token-review
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restore-vault-token-review
subjects:
  - kind: ServiceAccount
    name: restore-vault
    namespace: restore-vault
