apiVersion: v1
kind: ConfigMap
metadata:
  name: restore-vault
  namespace: restore-vault
data:
  vault.hcl: |
    ui = false
    disable_mlock = true
    api_addr = "http://127.0.0.1:8200"
    listener "tcp" {
      tls_disable = 1
      address = "0.0.0.0:8200"
      cluster_address = "127.0.0.1:8201"
    }
    storage "file" {
      path = "/vault/data"
    }
    seal "awskms" {}
