apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secrets
  namespace: arr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: homepage-secrets
  data:
    - secretKey: HOMEPAGE_VAR_JELLYFIN_KEY
      remoteRef:
        key: apps/homepage
        property: HOMEPAGE_VAR_JELLYFIN_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HOMEPAGE_VAR_SEERR_KEY
      remoteRef:
        key: apps/homepage
        property: HOMEPAGE_VAR_SEERR_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HOMEPAGE_VAR_SONARR_KEY
      remoteRef:
        key: apps/homepage
        property: HOMEPAGE_VAR_SONARR_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HOMEPAGE_VAR_RADARR_KEY
      remoteRef:
        key: apps/homepage
        property: HOMEPAGE_VAR_RADARR_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HOMEPAGE_VAR_PROWLARR_KEY
      remoteRef:
        key: apps/homepage
        property: HOMEPAGE_VAR_PROWLARR_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HOMEPAGE_VAR_BAZARR_KEY
      remoteRef:
        key: apps/homepage
        property: HOMEPAGE_VAR_BAZARR_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HOMEPAGE_VAR_QBIT_PASSWORD
      remoteRef:
        key: apps/homepage
        property: HOMEPAGE_VAR_QBIT_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
