apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vpn-credentials
  namespace: arr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: vpn-credentials
  data:
    - secretKey: OPENVPN_USER
      remoteRef:
        key: apps/vpn
        property: OPENVPN_USER
    - secretKey: OPENVPN_PASSWORD
      remoteRef:
        key: apps/vpn
        property: OPENVPN_PASSWORD
