apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-raft-data
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
