injector:
  enabled: false
server:
  statefulSet:
    securityContext:
      pod:
        runAsUser: 100
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      container:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
  volumes:
    - name: tmp
      emptyDir: {}
    - name: raft-data
      persistentVolumeClaim:
        claimName: vault-raft-data
  volumeMounts:
    - name: tmp
      mountPath: /tmp
    - name: raft-data
      mountPath: /vault/data
  extraSecretEnvironmentVars:
    - envName: AWS_ACCESS_KEY_ID
      secretName: vault-aws-kms
      secretKey: AWS_ACCESS_KEY_ID
    - envName: AWS_SECRET_ACCESS_KEY
      secretName: vault-aws-kms
      secretKey: AWS_SECRET_ACCESS_KEY
    - envName: AWS_REGION
      secretName: vault-aws-kms
      secretKey: AWS_REGION
    - envName: VAULT_AWSKMS_SEAL_KEY_ID
      secretName: vault-aws-kms
      secretKey: VAULT_AWSKMS_SEAL_KEY_ID
  standalone:
    enabled: false
  dataStorage:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
  ha:
    disruptionBudget:
      enabled: false
    enabled: true
    replicas: 1
    raft:
      enabled: true
      config: |
        disable_mlock = true
        ui = true

        listener "tcp" {
          tls_disable = 1
          address     = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path = "/vault/data"
          node_id = "vault-0"
        }

        seal "awskms" {}
ui:
  enabled: true
