injector:
  enabled: false
server:
  statefulSet:
    securityContext:
      pod:
        runAsUser: 100
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
      container:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
          add:
            - IPC_LOCK
  extraSecretEnvironmentVars:
    - envName: AWS_ACCESS_KEY_ID
      secretName: vault-aws-kms
      secretKey: AWS_ACCESS_KEY_ID
    - envName: AWS_SECRET_ACCESS_KEY
      secretName: vault-aws-kms
      secretKey: AWS_SECRET_ACCESS_KEY
    - envName: AWS_REGION
      secretName: vault-aws-kms
      secretKey: AWS_REGION
    - envName: VAULT_AWSKMS_SEAL_KEY_ID
      secretName: vault-aws-kms
      secretKey: VAULT_AWSKMS_SEAL_KEY_ID
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address     = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "file" {
        path = "/vault/data"
      }

      seal "awskms" {}
  dataStorage:
    enabled: true
    size: 1Gi
    storageClass: nfs-client
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
ui:
  enabled: true
