schedule: '*/30 * * * *'
deschedulerPolicy:
  profiles:
    - name: default
      pluginConfig:
        - name: RemoveDuplicates
          args:
            excludeOwnerKinds:
              - DaemonSet
        - name: LowNodeUtilization
          args:
            thresholds:
              cpu: 20
              memory: 20
              pods: 20
            targetThresholds:
              cpu: 50
              memory: 50
              pods: 50
        - name: RemovePodsHavingTooManyRestarts
          args:
            podRestartThreshold: 10
            includingInitContainers: true
      plugins:
        balance:
          enabled:
            - RemoveDuplicates
            - LowNodeUtilization
        deschedule:
          enabled:
            - RemovePodsHavingTooManyRestarts
resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    memory: 128Mi
