apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arr-sonarr-env
  namespace: arr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: arr-sonarr-env
  data:
    - secretKey: SONARR__AUTH__APIKEY
      remoteRef:
        key: apps/arr
        property: sonarr-api-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arr-radarr-env
  namespace: arr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: arr-radarr-env
  data:
    - secretKey: RADARR__AUTH__APIKEY
      remoteRef:
        key: apps/arr
        property: radarr-api-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arr-prowlarr-env
  namespace: arr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: arr-prowlarr-env
  data:
    - secretKey: PROWLARR__AUTH__APIKEY
      remoteRef:
        key: apps/arr
        property: prowlarr-api-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arr-api-keys
  namespace: arr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: arr-api-keys
  data:
    - secretKey: sonarr-api-key
      remoteRef:
        key: apps/arr
        property: sonarr-api-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: radarr-api-key
      remoteRef:
        key: apps/arr
        property: radarr-api-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: prowlarr-api-key
      remoteRef:
        key: apps/arr
        property: prowlarr-api-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-credentials
  namespace: arr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: qbittorrent-credentials
    template:
      engineVersion: v2
      data:
        username: admin
        password: "{{ .password }}"
        password-pbkdf2: '{{ index . "password-pbkdf2" }}'
  data:
    - secretKey: password
      remoteRef:
        key: apps/unpackerr
        property: UN_QBIT_0_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password-pbkdf2
      remoteRef:
        key: apps/qbittorrent
        property: webui-password-pbkdf2
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-credentials
  namespace: arr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: jellyfin-credentials
  data:
    - secretKey: username
      remoteRef:
        key: apps/jellyfin
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: apps/jellyfin
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
