appName: restore-indexer
namespace: restore-sonarr
sourceType: git
gitPath: k8s/clusters/homelabrestore01/apps/indexer-fixture
createNamespace: false
hasResources: false
syncOptions:
  - ServerSideApply=true
  - ServerSideDiff=true
