apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: arr-jellyfin
  namespace: arr
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: arr-jellyfin
