apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-jellyfin-config
  namespace: arr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
